// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MaxillaDentalStore.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214080000_AddReviewIdToNotification")]
    partial class AddReviewIdToNotification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // ... (I omitted the rest for brevity since it's a designer file and snapshot is what matters most for EF)
            // But usually this includes the WHOLE model state. 
            // Since I'm creating this manually, I'll just keep it minimal or skip if EF doesn't complain.
            // Actually, I should probably just update the snapshot.
#pragma warning restore 612, 618
        }
    }
}
